apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chromadb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DmMustafa/gitops-aiops-demo.git
    targetRevision: HEAD
    path: manifests/chromadb
  destination:
    server: https://kubernetes.default.svc
    namespace: chromadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
